### ISSUE TITLE
Install rahat to your environment and send us your feedback.

### ISSUE THREAD

**Issue by nishu-rumsan** [esatya/rahat#218]
Install [rahat](https://github.com/esatya/rahat) to your environment by following the sets listed in [Readme](https://github.com/esatya/rahat#readme). 

When installing Rahat projects in your environment, how easy was the process? 

Share your feedback and suggestions about the installation process [here](https://github.com/esatya/rahat/discussions/214). </div>

**Comment by RegishShrestha** [comment]
okay Can i do this?

**Comment by Nishubade** [comment]
> okay Can i do this?

Yes, Sure. Follow the [Readme](https://github.com/esatya/rahat#readme). and Share your feedbacks https://github.com/esatya/rahat/discussions/214.
